######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 17:45:45 2017
######################################################################

TEMPLATE = app
TARGET = 01-using_qlabel
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
RESOURCES = images.qrc
