######################################################################
# Automatically generated by qmake (3.1) Thu Jan 25 15:02:21 2018
######################################################################

TEMPLATE = app
TARGET = 05-observer_program
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
