######################################################################
# Automatically generated by qmake (3.1) Sun Jan 29 10:53:20 2017
######################################################################

TEMPLATE = app
TARGET = 05-nested_layouts
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
