######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 21:41:40 2017
######################################################################

TEMPLATE = app
TARGET = 06-using_lcd_number
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
