######################################################################
# Automatically generated by qmake (3.1) Sat Jan 28 17:18:27 2017
######################################################################

TEMPLATE = app
TARGET = 03-simple_frame_creating
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp 
