######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 20:00:14 2017
######################################################################

TEMPLATE = app
TARGET = 03-using_ampersands_with_labels
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
