######################################################################
# Automatically generated by qmake (3.0) ?? ????. 22 23:00:44 2016
######################################################################

TEMPLATE = app
TARGET = 11_connecting_signals
INCLUDEPATH += .

# Input
HEADERS += MyClass.hpp
SOURCES += main.cpp
