######################################################################
# Automatically generated by qmake (3.1) Sat Jan 28 18:45:00 2017
######################################################################

TEMPLATE = app
TARGET = 01-buttons_with_stretching
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
