######################################################################
# Automatically generated by qmake (3.0) ?? ????. 6 19:55:43 2016
######################################################################

TEMPLATE = app
TARGET = 5_slot
INCLUDEPATH += .

# Input
HEADERS += MySlot.h
SOURCES += main.cpp
