######################################################################
# Automatically generated by qmake (3.1) Sun Mar 12 17:22:22 2017
######################################################################

TEMPLATE = app
TARGET = 02-qtextedit_example
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
RESOURCES += images.qrc
