######################################################################
# Automatically generated by qmake (3.1) Thu May 4 20:16:06 2017
######################################################################

TEMPLATE = app
TARGET = 01-model_selection
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic
QT += widgets

# Input
SOURCES += main.cpp
