######################################################################
# Automatically generated by qmake (3.0) ?? ????. 22 16:22:58 2016
######################################################################

TEMPLATE = app
TARGET = 10_small_application_with_signal_and_slots
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += Counter.hpp
SOURCES += Counter.cpp main.cpp
