######################################################################
# Automatically generated by qmake (3.0) ?? ????? 13 20:23:45 2016
######################################################################

TEMPLATE = app
TARGET = 14_connecting_slots_using_smart_pointers
INCLUDEPATH += .

# Input
HEADERS += MyClass.hpp
SOURCES += main.cpp
