######################################################################
# Automatically generated by qmake (3.1) Sun Feb 26 19:37:04 2017
######################################################################

TEMPLATE = app
TARGET = 02-a_button_with_a_menu
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
