######################################################################
# Automatically generated by qmake (3.1) Sat Jan 28 19:00:08 2017
######################################################################

TEMPLATE = app
TARGET = 02-buttons_with_independent_stretching
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
