; [exercise] =>
; Each of the following two procedures
; defines a method for adding two positive integers
; in terms of the procedures `inc`,
; which increments its argument by 1,
; and `dec`, which decrements its argument by 1.
;
; ```
; (define (+ a b)
;   (if (= a 0) b (inc (+ (dec a) b))))
;
; (define (+ a b)
;   (if (= a 0) b (+ (dec a)(dec b))))
; ```
;
; Using the substitution model, illustrate the process
; generated by each procedure in evaluating `(+ 4 5)`.
; Are these process iterative or recursive?


; -------------
; [solution] =>
#lang sicp
(define (inc a) (+ a 1))
(define (dec a) (- a 1))

; the `plus1` procedure
(define (plus1 a b)
    (if (= a 0)
        b
        (inc (plus1 (dec a) b))))

(display (plus1 4 5))(newline)

; the `plus1` procedure process:
; (plus1 4 5)
; (inc (plus1 3 5))
; (inc (inc (plus1 2 5)))
; (inc (inc (inc (plus1 1 5))))
; (inc (inc (inc (inc (plus1 0 5)))))
; (inc (inc (inc (inc 5))))
; 9


; the `plus2` procedure
(define (plus2 a b)
    (if (= a 0) b (plus2 (dec a)(inc b))))

(display (plus2 4 5))(newline)

; the `plus2` procedure process
; (plus2 4 5)
; (plus2 3 6)
; (plus2 2 7)
; (plus2 1 8)
; (plus2 0 9)
; 9


; conclusion
; `plus1` is a linear recursive process
; 'plus2' is an iterative process
