######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 21:17:25 2017
######################################################################

TEMPLATE = app
TARGET = 05-using_progress_bar
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
HEADERS += progress.hpp
SOURCES += main.cpp progress.cpp
