######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 18:32:19 2017
######################################################################

TEMPLATE = app
TARGET = 02-using_qlabel_without_html
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
RESOURCES += images.qrc
