######################################################################
# Automatically generated by qmake (3.1) Mon Feb 27 21:08:25 2017
######################################################################

TEMPLATE = app
TARGET = 03-checkbox_using
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
