######################################################################
# Automatically generated by qmake (3.1) Thu Jan 25 14:41:21 2018
######################################################################

TEMPLATE = app
TARGET = 03-hierachical_data_showing
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
