######################################################################
# Automatically generated by qmake (3.1) Sun Jan 29 11:40:21 2017
######################################################################

TEMPLATE = app
TARGET = 07-creating_a_layout_for_a_calculator
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
HEADERS += Calculator.h
SOURCES += main.cpp Calculator.cpp
