######################################################################
# Automatically generated by qmake (3.0) ?? ????? 13 20:06:56 2016
######################################################################

TEMPLATE = app
TARGET = 14_object_hierarchy_creation
INCLUDEPATH += .

# Input
SOURCES += main.cpp
