######################################################################
# Automatically generated by qmake (3.1) Thu Apr 20 20:23:52 2017
######################################################################

TEMPLATE = app
TARGET = 01-simple_list_example
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic
QT += widgets

# Input
SOURCES += main.cpp
RESOURCES += images.qrc
