######################################################################
# Automatically generated by qmake (3.1) Thu Apr 27 19:47:49 2017
######################################################################

TEMPLATE = app
TARGET = 05-combobox
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic
QT += widgets

# Input
SOURCES += main.cpp
