######################################################################
# Automatically generated by qmake (3.1) Sun Mar 5 23:41:50 2017
######################################################################

TEMPLATE = app
TARGET = 01_qlineedit_example
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
