######################################################################
# Automatically generated by qmake (3.1) Sat Apr 29 11:34:05 2017
######################################################################

TEMPLATE = app
TARGET = 06-tabs_using
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic
QT += widgets

# Input
SOURCES += main.cpp
RESOURCES += images.qrc
