######################################################################
# Automatically generated by qmake (3.1) Sat Jan 28 17:30:55 2017
######################################################################

TEMPLATE = app
TARGET = 04-using_a_scroll_area
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
RESOURCES = images.qrc
