######################################################################
# Automatically generated by qmake (3.1) Mon Feb 27 21:30:15 2017
######################################################################

TEMPLATE = app
TARGET = 05-groupbox_using
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wextra -Wall -pedantic

# Input
HEADERS += buttons.hpp
SOURCES += buttons.cpp main.cpp
