######################################################################
# Automatically generated by qmake (3.1) Thu Jan 25 14:18:31 2018
######################################################################

TEMPLATE = app
TARGET = 02-delegate
INCLUDEPATH += .

QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
