######################################################################
# Automatically generated by qmake (3.0) ?? ????. 6 19:14:18 2016
######################################################################

TEMPLATE = app
TARGET = 2
INCLUDEPATH += .

# Input
HEADERS += MyClass.h
SOURCES += main.cpp
