######################################################################
# Automatically generated by qmake (3.1) Sun Mar 19 15:08:16 2017
######################################################################

TEMPLATE = app
TARGET = 04-syntax_highlighting
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
HEADERS += SyntaxHighlighter.hpp
SOURCES += main.cpp SyntaxHighlighter.cpp
