######################################################################
# Automatically generated by qmake (3.1) Thu Jan 25 19:03:52 2018
######################################################################

TEMPLATE = app
TARGET = 06-role_using
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
