######################################################################
# Automatically generated by qmake (3.1) Sun Mar 19 15:14:04 2017
######################################################################

TEMPLATE = app
TARGET = 06-using_qdatetime
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
