######################################################################
# Automatically generated by qmake (3.1) Sun Mar 19 15:09:16 2017
######################################################################

TEMPLATE = app
TARGET = 05-qspinbox_using
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
