######################################################################
# Automatically generated by qmake (3.1) Sun Mar 19 14:03:36 2017
######################################################################

TEMPLATE = app
TARGET = 03-writing_odf_and_pdf_to_file
INCLUDEPATH += .
QT += widgets printsupport
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
