######################################################################
# Automatically generated by qmake (3.1) Sun Jan 29 11:32:16 2017
######################################################################

TEMPLATE = app
TARGET = 06-simple_using_of_qgridlayout
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
