######################################################################
# Automatically generated by qmake (3.1) Thu Jan 25 14:52:35 2018
######################################################################

TEMPLATE = app
TARGET = 04-folder_and_file_showing
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
