######################################################################
# Automatically generated by qmake (3.0) ?? ????. 22 23:21:42 2016
######################################################################

TEMPLATE = app
TARGET = 12_signal_overloading
INCLUDEPATH += .

# Input
HEADERS += MyClass.hpp
SOURCES += main.cpp
