######################################################################
# Automatically generated by qmake (3.1) Sun Mar 19 15:25:26 2017
######################################################################

TEMPLATE = app
TARGET = 07-using_qvalidator
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic


# Input
SOURCES += main.cpp
