######################################################################
# Automatically generated by qmake (3.1) Sat Jan 28 10:09:40 2017
######################################################################

TEMPLATE = app
TARGET = 01-creating_simple_widgets
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
RESOURCES = images.qrc
