######################################################################
# Automatically generated by qmake (3.1) Mon Apr 24 20:17:57 2017
######################################################################

TEMPLATE = app
TARGET = 04-tables
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic
QT += widgets

# Input
SOURCES += main.cpp
