######################################################################
# Automatically generated by qmake (3.0) ?? ????? 13 18:50:23 2016
######################################################################

TEMPLATE = app
TARGET = 13_disconecting_slots_and_signals
INCLUDEPATH += .

# Input
HEADERS += MyClass.hpp
SOURCES += main.cpp
