######################################################################
# Automatically generated by qmake (3.1) Fri Mar 3 21:08:23 2017
######################################################################

TEMPLATE = app
TARGET = 01-slider_example
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
