######################################################################
# Automatically generated by qmake (3.1) Sat Jan 28 19:14:38 2017
######################################################################

TEMPLATE = app
TARGET = 03-using_hbox_layout
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
