######################################################################
# Automatically generated by qmake (3.1) Sun Apr 23 11:20:35 2017
######################################################################

TEMPLATE = app
TARGET = 03-hierachical_list
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic
QT += widgets

# Input
SOURCES += main.cpp
RESOURCES += images.qrc
