######################################################################
# Automatically generated by qmake (3.1) Sat Apr 22 10:53:32 2017
######################################################################

TEMPLATE = app
TARGET = 02-pictogram_mode
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic
QT += widgets

# Input
SOURCES += main.cpp
RESOURCES += images.qrc
