######################################################################
# Automatically generated by qmake (3.1) Sun Feb 4 20:22:22 2018
######################################################################

TEMPLATE = app
TARGET = 08-table_model
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
HEADERS += table_model.hpp
SOURCES += main.cpp
