######################################################################
# Automatically generated by qmake (3.1) Thu Jan 25 20:27:06 2018
######################################################################

TEMPLATE = app
TARGET = 07-int_list_model
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
HEADERS += int_list_model.hpp
SOURCES += main.cpp
