######################################################################
# Automatically generated by qmake (3.1) Sat Apr 29 12:33:12 2017
######################################################################

TEMPLATE = app
TARGET = 07-toolbox_using
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic
QT += widgets

# Input
SOURCES += main.cpp
RESOURCES += images.qrc
