######################################################################
# Automatically generated by qmake (3.1) Sat Jan 28 17:03:53 2017
######################################################################

TEMPLATE = app
TARGET = 02-mouse_pointer_change
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
RESOURCES = images.qrc
