######################################################################
# Automatically generated by qmake (3.0) ?? ???. 22 21:13:14 2016
######################################################################

TEMPLATE = app
TARGET = 01_the_first_qt_program
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
