######################################################################
# Automatically generated by qmake (3.1) Sun Jan 29 12:45:53 2017
######################################################################

TEMPLATE = app
TARGET = 08-using_qsplitter
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
