######################################################################
# Automatically generated by qmake (3.0) ?? ????. 6 19:46:00 2016
######################################################################

TEMPLATE = app
TARGET = 4_signal
INCLUDEPATH += .

# Input
HEADERS += MySignal.hpp
SOURCES += main.cpp
