######################################################################
# Automatically generated by qmake (3.1) Sat Jan 28 19:24:33 2017
######################################################################

TEMPLATE = app
TARGET = 04-using_vbox_layout
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
