######################################################################
# Automatically generated by qmake (3.1) Sun Feb 26 19:18:34 2017
######################################################################

TEMPLATE = app
TARGET = 01-push_button_using
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
RESOURCES += images.qrc

