######################################################################
# Automatically generated by qmake (3.0) ?? ????. 6 19:41:45 2016
######################################################################

TEMPLATE = app
TARGET = 3_signal
INCLUDEPATH += .

# Input
HEADERS += MySignal.h
SOURCES += main.cpp
