######################################################################
# Automatically generated by qmake (3.1) Sun Jul 2 21:50:42 2017
######################################################################

TEMPLATE = app
TARGET = 01-creating_gui_from_code
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
