######################################################################
# Automatically generated by qmake (3.1) Fri Feb 24 20:24:28 2017
######################################################################

TEMPLATE = app
TARGET = 04-using_web_links_with_labels
INCLUDEPATH += .
QT += widgets
QMAKE_CXXFLAGS += -std=c++14 -Wall -Wextra -pedantic

# Input
SOURCES += main.cpp
